AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless image processing app - Resize images uploaded to S3

Resources:
  # Lambda Function
  ResizeImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: image-resize/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 30

      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource:
                - "arn:aws:s3:::original-images-hamzamufeed"
                - "arn:aws:s3:::original-images-hamzamufeed/*"
                - "arn:aws:s3:::processed-images-hamzamufeed"
                - "arn:aws:s3:::processed-images-hamzamufeed/*"

      Events:
        # Trigger Lambda when an object is uploaded to OriginalImagesBucket
        S3UploadTrigger:
          Type: S3
          Properties:
            Bucket: original-images-hamzamufeed
            Events: s3:ObjectCreated:*